version: "3"
services:
  backend:
    build: .
    depends_on:
      - "mysql"
    links:
      - mysql
    ports:
      - "8080:8080"
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 123Group3@.